export const products = [
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '10',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '2',
  },
  {
    image: '',
    storeName: '',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '23',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
  {
    image: '',
    storeName: 'Galaxy',
    name: 'Lorem ipsum',
    descrption: 'Lorem ipsum dolor sit amet consectetur.',
    inStock: '332',
  },
];
